name: kafkacat-images
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/kafkacat-images
semaphore:
  enable: true
  pipeline_enable: false
codeowners:
  enable: true

